### ISSUE TITLE
Feedback: 2019-07-07 Login System UML

### ISSUE THREAD

**Issue by Jozdortraz** [draupnirstudio/Fafnir#2]
## Swim Lane Diagram
1. There should be a ‘Server’ column between the ‘Application’ & ‘Database’
2. Customer’s Browser should not be in this swim lane diagram since the browser cannot make an action(a browser cannot insert email, but customers can). you need to rearrange all the actions in Browser column to the right place.
3. In Customer column, Welcome Page, Error Page... are not actions. Remember, rectangles are actions.
4. Try not to intersect the lines, you need to use a tiny arc (like `Ω`) across the line.
5. When the customer enters the error page, the application should let customers re-enter their email rather than directly end the process.
6. The database cannot authorize email & password, the server can. (Although some gangjing(杠精) may say that we can use stored procedures to validate the credentials, it’s not recommended to use procedures in the database(procedures suck in distributed systems) 
7. If you need to draw two lines from one action, e.g. `Customer -> Try to use the application -> sign in / sign up`, use option(diamond, ◇) rather than separate the lines.

## Activity Diagram
1. What does the shape of `Sign In` means?
2. If the user attempted 3 times, the system will reject future login requests, please draw it on the diagram.
3. Also, it’s the very server authorize the credential, not the database.

## Class Diagram
- Your class diagram should not have User Browser, Sign in Page, Sign Up Page, Database, etc. The class diagram is all about the data model. 

## ER Diagram
- If you don’t know what the ER Diagram is, you can use Google.

Please fix.

**Comment by Mengqi29** [comment]
### Updated Swimlane diagram:
![swimlane](https://user-images.githubusercontent.com/43154273/60851912-88f59000-a1c3-11e9-8f2e-d1743090814e.png)

### Updated Flowchart diagram:
![flowchart](https://user-images.githubusercontent.com/43154273/60852174-8e070f00-a1c4-11e9-9530-fbcdce98a5db.png)

**Comment by Jozdortraz** [comment]
@Mengqi29 Great! Your UML grammar is perfect. 

There are still some misplaced actions due to the lack of concept of what an auth system should be. Don't worry, we will cover all of the auth systems in the next two weeks. After that, you may draw the whole process correctly.
